version: '3'
services:
  app:
    build: .
    image: paulasch/twittstorm
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN_KEY=${TWITTER_ACCESS_TOKEN_KEY}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - MAPBOX_ACCESS_KEY=${MAPBOX_ACCESS_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - mongodbservice
  mongodbservice:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/mongodb/db
